title: Allan Reyes Design Portfolio
baseURL: /
params:
  accent_color: yellow
  color_scheme: dark
  footer:
    content: '&copy; 2020 Allan Reyes.'
    has_social: true
  header:
    has_nav: true
    logo_img: /images/ar-logo-main-gray.svg
    title: Allan Reyes
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
